#!/usr/bin/bash

VERBOS=0
NUM=5
INTERVAL=10
SUCCESS=1
 function help {
         cat <<EOF
Usage: $0 [OPTIONS] <COMMAND>
Available Options:
         -h : Display this help and exit
         -v : Verbos mode
         -n : Number of tries (Default: 5)
         -i : Interval seconds (Default: 10)
Examples:
        $0 -v COMMAND
        $0 -v -n 3 -i 2 COMMAND
        $0 -v -i 5 COMMAND
        $0 -i 5 -n 2 COMMAND

EOF
 }

 function check_number {
         if [[  "$1" =~ ^[0-9]+$ ]]; then
            return 0
          else
            return 1
         fi
 }

 if [[ $# -eq 0 ]]; then
   help
   exit 0
 fi


 while [[ $# -ne 0 ]]; do

        case $1 in
        -h)
                help
                 exit 0
                ;;
        -v)
				VERBOS=1
				shift
                ;;
         -n)
                check_number $2
				if [[ $? -ne 0 ]]; then
				  help
				  exit 1
				fi
				NUM=$2
				shift 2
                ;;
         -i)
                check_number $2
				if [[ $? -ne 0 ]]; then
					help
					exit 1
				fi
				INTERVAL=$2
				shift 2
				;;
          *)
				COMMAND=$@
				break
				;;
		esac
 done
 echo $VERBOS
 echo $NUM
 echo $INTERVAL
 echo $COMMAND
 if [[ -z $COMMAND ]]; then
    help
    exit 1
  fi
for i in `seq 1 $NUM`; do
	$($COMMAND)
	if [[ $? -eq 0 ]]; then
		SUCCESS=0
		break
	else 
		if [[ $VERBOS -eq 1 ]]; then
		  echo "[INFO]: Try $i failed sleep for $INTERVAL seconds"		
		fi
		sleep $INTERVAL
	fi
done
if [[ $SUCCESS -eq 0 ]]; then
    if [[ $VERBOS -eq 1 ]]; then     
      echo "[INFO]: The $COMMAND got executed seccessfully"
    fi
    exit 0
 else
    if [[ $VERBOS -eq 1 ]]; then   
	  echo "[ERROR]: reached the threshold but $COMMAND did not run seccessfully"
    fi
    exit 1
 fi
 


